# Generated by Django 2.2.7 on 2020-01-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutType',
        ),
    ]
