# Generated by Django 2.2.7 on 2020-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('politeness', models.IntegerField(blank=True, null=True)),
                ('punctuality', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_comment',
                'managed': False,
            },
        ),
    ]
