# Generated by Django 2.2.7 on 2020-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_authuser_gender_privacyrules_projectrules_publicoffer_users_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('photo_main', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/advert/')),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('count_offer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_advert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('pay', models.TextField(blank=True, null=True)),
                ('photo_main', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/task/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
                ('rezult_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('exec_finish', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_task_status',
                'managed': False,
            },
        ),
    ]
